apiVersion: v1
kind: Service
metadata:
  annotations:
    version: 1.34.0
  labels:
    app: tracker
  name: tracker
spec:
  ports:
    - name: http
      port: {{ .Values.trackerServer.port }}
      targetPort: {{ .Values.trackerServer.port }}
      protocol: TCP
    - name: "grpc"
      port: {{ .Values.trackerServer.grpcServerPort }}
      targetPort: {{ .Values.trackerServer.grpcServerPort }}
      protocol: TCP
  selector:
    app: tracker
    traffic: active